import { execFile } from "node:child_process"
import { readFile } from "node:fs/promises"
import { promisify } from "node:util"

import { describe, expect, it } from "vitest"

const execFileAsync = promisify(execFile)
const actionReference = /uses:\s+[^\s@]+@([0-9a-f]{40})/g
const workspaceRoot = process.cwd()

async function readWorkspaceFile(path: string) {
  return readFile(`${workspaceRoot}/${path}`, "utf8")
}

describe("repository controls", () => {
  it("uses immutable, least-privilege GitHub Actions and tracks updates", async () => {
    const workflows = await Promise.all(
      [
        ".github/workflows/verify.yml",
        ".github/workflows/release-canary.yml",
      ].map(readWorkspaceFile)
    )
    const actions = workflows.flatMap((workflow) => [
      ...workflow.matchAll(actionReference),
    ])
    const dependabot = await readWorkspaceFile(".github/dependabot.yml")

    expect(actions.length).toBeGreaterThan(0)
    expect(actions.every(([, sha]) => /^[0-9a-f]{40}$/.test(sha))).toBe(true)
    expect(
      workflows.every((workflow) => workflow.includes("contents: read"))
    ).toBe(true)
    expect(
      workflows.every((workflow) =>
        /actions\/checkout@[0-9a-f]{40}\s+#\s+v[\d.]+\n\s+with:\n\s+persist-credentials: false/.test(
          workflow
        )
      )
    ).toBe(true)
    expect(dependabot).toContain("package-ecosystem: github-actions")
  })

  it("uses pinned portable MCP commands in every committed client configuration", async () => {
    const configurations = await Promise.all(
      [
        ".mcp.json",
        ".cursor/mcp.json",
        ".kiro/settings/mcp.json",
        ".qoder/mcp.json",
        ".vscode/mcp.json",
      ].map(async (path) => JSON.parse(await readWorkspaceFile(path)))
    )

    for (const configuration of configurations) {
      const server = (configuration.mcpServers ?? configuration.servers)[
        "code-review-graph"
      ]
      expect(server).toMatchObject({ command: "uvx", cwd: ".", type: "stdio" })
      expect(server.args).toEqual([
        "--from",
        "code-review-graph==2.3.8",
        "code-review-graph",
        "serve",
      ])
      expect(JSON.stringify(server)).not.toContain("/home/")
    }
  })

  it("publishes Apache-2.0 legal metadata and a reproducible attribution report", async () => {
    const manifests = await Promise.all(
      [
        "package.json",
        "packages/ui/package.json",
        "packages/eslint-config/package.json",
        "packages/typescript-config/package.json",
      ].map(async (path) => JSON.parse(await readWorkspaceFile(path)))
    )
    const [license, notice, security, owners, support, release, attributions] =
      await Promise.all(
        [
          "LICENSE",
          "NOTICE",
          "SECURITY.md",
          ".github/CODEOWNERS",
          "SUPPORT.md",
          "RELEASE.md",
          "THIRD_PARTY_NOTICES.md",
        ].map(readWorkspaceFile)
      )

    expect(
      manifests.every((manifest) => manifest.license === "Apache-2.0")
    ).toBe(true)
    expect(license).toContain("Apache License")
    expect(notice).toContain("Naneware Labs")
    expect(notice).toContain("2026")
    expect(security).toMatch(/security\s+advisory/)
    expect(owners).toContain("@miannilisso")
    expect(support).toContain("GitHub Issues")
    expect(release).toContain("Semantic Versioning")
    expect(attributions).toContain("Generated by pnpm licenses list")

    await expect(
      execFileAsync(
        "node",
        ["scripts/generate-third-party-attributions.mjs", "--check"],
        {
          cwd: workspaceRoot,
        }
      )
    ).resolves.toMatchObject({ stderr: "" })
  }, 15_000)
})
